/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Account.vue')['default']
    Address: typeof import('./src/components/Address.vue')['default']
    Blockie: typeof import('./src/components/Blockie.vue')['default']
    Blockies: typeof import('./src/components/Blockies.vue')['default']
    Connect: typeof import('./src/components/Connect.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
